# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 335dee1e8e2578130766245eacc956f0debd4d5a2d602f38a522d9258b97e14c00091b564e8e17e90b48bae681ae3344c8a044cb5db3bd69c68dc3122d982de6

test:
  secret_key_base: 4c9ae5b501bb0751632e2f1885a2295e02353a6615eaed1fcf498e1f706d53b963a29f58b4aae9adc76a13392bcea6f63da5ffd97217589cdcf87237b3f96be7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
